language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install -r /Website/requirements.txt
# command to run tests
script: python -m unittest discover Iteration\ 1/Test\ Cases/Testing\ Scripts/
